// THIS FILE IS AUTOGENERATED from the parameters in config.json. Do not edit it.
// If you want to change something about how it's generated, look at library/asset_builder.ts.

import { TypesafeLoader } from "../library/typesafe_loader";

export type AssetType =
  | "Image"
  | "TileMap"
  | "TileWorld"
  | "Audio"
  | "Spritesheet"
  | "Animation"

export type AssetName = keyof typeof AssetsToLoad
export type AssetPath = 
  | "map.json"
  | "module_dialog.png"
  | "npc_sheet.png"
  | "player_sheet.png"
  | "tileset.png"



export const AssetsToLoad = {
  "map"          : { type: "TileMap"     as const, path: "map.json"          },
  "module_dialog": { type: "Image"       as const, path: "module_dialog.png" },
  "npc"          : { type: "SpriteSheet" as const, path: "npc_sheet.png"     },
  "player"       : { type: "SpriteSheet" as const, path: "player_sheet.png"  },
  "tileset"      : { type: "Image"       as const, path: "tileset.png"       },
};

export const Assets = new TypesafeLoader(AssetsToLoad);
